#!/usr/bin/env python3

import sys
import locale

locale.setlocale(locale.LC_ALL, 'en_IN.UTF-8')  # en_US.UTF-8 for USD


def money_str(amt):
    # return "{:,.2f}".format(amt)
    return locale.currency(amt, grouping=True)


def print_yr_money(purpose, yr, current_save, current_spend, spent_amount):
    saved_money = money_str(current_save)
    spent_money = money_str(current_spend)
    tot_spent_money = money_str(spent_amount)
    if purpose in ["spend", "spent"]:
        msg = "at %-2s year:\t[spent] %s | total: %s"
        print(msg % (yr, spent_money, tot_spent_money))
    elif purpose in ["save", "saved"]:
        msg = "at %-2s year:\t[saved] %s"
        print(msg % (yr, saved_money))
    elif purpose == "all":
        msg = "at %-2s year:\t[saved] %s\t[spent] %s (%s)"
        print(msg % (yr, saved_money, spent_money, tot_spent_money))


def print_help():
    print("""usage:
    %s <money-amount> <number-of-years> <rate-%%> [<spend|saved|all>]"""
          % sys.argv[0])


def do_lumpsum(args):
    amount = float(args[0])
    years = int(args[1])
    percent = float(args[2])/100
    purpose = ""
    if len(args) > 3:
        purpose = str(args[3])
    if purpose not in ["spend", "spent", "save", "saved"]:
        purpose = "all"
    current_save = amount
    current_spend = amount
    spent_amount = amount
    print("%s | %d | %f | %s" % (money_str(amount), years, percent, purpose))
    print_yr_money(purpose, 0, current_save, current_spend, spent_amount)
    for yr in range(1, years+1):
        _prev_save = current_save
        _prev_spent = current_spend
        current_save = _prev_save + (_prev_save*percent)
        current_spend = _prev_spent + (_prev_spent*percent) 
        spent_amount += current_spend
        print_yr_money(purpose, yr, current_save, current_spend, spent_amount)
    if purpose in ["spend", "spent", "all"]:
        print("\ntotal spending would be:\t", money_str(spent_amount))
    if purpose in ["save", "saved", "all"]:
        print("\ntotal savings would be:\t", money_str(amount))


if len(sys.argv) < 4:
    if len(sys.argv) > 1 and sys.argv[1] in ["-h", "--help"]:
        print_help()
        sys.exit(0)
    print_help()
    sys.exit(1)
try:
    do_lumpsum(sys.argv[1:])
except Exception as e:
    print(e)
    print_help()
